# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:

  cartdata:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

# Explore switching to self-hosted App Gateway for local dev
# https://learn.microsoft.com/en-us/azure/api-management/self-hosted-gateway-overview
  envoygateway:
    image: envoygateway
    build: 
      context: .
      dockerfile: Gateways/Envoy/Dockerfile
    ports:
      - "9901:9901"
      - "80:7777"
#      - "10001:10001"    # Forget HTTPS in Container Environment
    deploy:
      resources:
        limits:
          memory: 128MB
        reservations:
          memory: 64MB
    memswap_limit: 128MB

  catalog-api:
    image: catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    deploy:
      resources:
        limits:
          memory: 128MB
        reservations:
          memory: 64MB
    memswap_limit: 128MB

  cart-api:
    image: cart-api
    build:
      context: .
      dockerfile: Services/Cart/Cart.API/Dockerfile
    deploy:
      resources:
        limits:
          memory: 128MB
        reservations:
          memory: 64MB
    memswap_limit: 128MB


  # catalogapi:
  #   image: catalogapi
  #   build:
  #     context: .
  #     dockerfile: Services/CatalogService/Dockerfile
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128MB
  #       reservations:
  #         memory: 64MB
  #   memswap_limit: 128MB

  # coffeeapi:
  #   image: coffeeapi
  #   build:
  #     context: .
  #     dockerfile: Services/Coffee/Coffee.API/Dockerfile
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128MB
  #       reservations:
  #         memory: 64MB
  #   memswap_limit: 128MB
