name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - Frontends/Angular/Me**
#  pull_request:
#    types: [opened, synchronize, reopened, closed]
#    branches:
#      - main

env:  
  WORKING_DIRECTORY: Frontends/Angular/Me
  OUTPUT_DIRECTORY: /dist/me

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - 
        name: Install Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      -
        name: Install Angular cli
        working-directory: ${{ env.WORKING_DIRECTORY }} 
        run: npm install -g @angular/cli@latest
      -
        name: Npm install
        working-directory: ${{ env.WORKING_DIRECTORY }} 
        run: npm install
      -
        name: Run tests
        working-directory: ${{ env.WORKING_DIRECTORY }} 
        run: ng test --no-watch --browsers=ChromeHeadless
      -
        name: Build application
        working-directory: ${{ env.WORKING_DIRECTORY }} 
        run: ng build --configuration production        
      - 
        name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.STATIC_WEB_APP_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_build_command: ng build --configuration production
          app_location: ${{ env.WORKING_DIRECTORY }}${{ env.OUTPUT_DIRECTORY }} # With skip_app_build, this is the deploy artifacts
          api_location: 'api' # Api source code path - optional
          output_location: '' # Built app content directory - optional
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: ${{ env.APP_LOCATION }} # App source code path
          azure_static_web_apps_api_token: ${{ secrets.STATIC_WEB_APP_DEPLOY_TOKEN }}
          action: "close"
      
